_base_: '../_base_/cityscapes.yml'

batch_size: 2
iters: 80000

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.05
  end_lr: 0.0
  power: 0.9

model:
  type: AttentionUNet
  pretrained: Null
