_base_: '../_base_/optic_disc_seg.yml'

model:
  type: FCN
  backbone:
    type: HRNet_W18
    pretrained: pretrained_model/hrnet_w18_imagenet
  num_classes: 19
  pretrained: Null
  backbone_indices: [-1]
