_base_: '../_base_/ade20k.yml'

batch_size: 8
iters: 40000

val_dataset:
  transforms:
    - type: ResizeByShort
      short_size: 512
    - type: Normalize
  mode: val

optimizer:
  type: AdamW
  _inherited_: False
  weight_decay: 1.0e-4

lr_scheduler:
  learning_rate: 0.0005
  power: 0.9
  end_lr: 1.0e-6

test_config:
  is_slide: True
  crop_size: [512, 512]
  stride: [512, 512]

model:
  type: EfficientFormerV2
  layers: [3, 3, 9, 6]
  embed_dims: [32, 48, 120, 224]
  downsamples: [True, True, True, True]
  fork_feat: True
  drop_path_rate: 0.
  vit_num: 2
  e_ratios: {
    '0': [4, 4, 4],
    '1': [4, 4, 4],
    '2': [4, 4, 3, 3, 3, 3, 4, 4, 4],
    '3': [4, 4, 3, 3, 4, 4],
  }
  pretrained: pretrained/eformer_s_2_pretrained.pdparams
