# As img nums = 100w, when bs=64, iters=50w, the epoch = 32  
batch_size: 64
iters: 500000

# ImagenetPseudoSeg only has train dataset.
train_dataset:
  type: ImagenetPseudoSeg
  dataset_root: /ssd3/pengjuncai/dataset/imagenet
  transforms:
    - type: ResizeByLong
      long_size: 256
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
    - type: RandomRotation
      max_rotation: 10
      label_padding_value: 1002
    - type: RandomPaddingCrop
      crop_size: [256, 256]
      label_padding_value: 1002
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.2
      contrast_range: 0.2
      saturation_range: 0.2
    - type: Normalize
  mode: train

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

# 把背景的权重设成了0.1。
loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
  
