_base_: './pp_mobileseg_base_ade20k_512x512_80k.yml'

batch_size: 16  # total batch size is 16
iters: 160000

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.0004
  end_lr: 0
  power: 1.0
  warmup_iters: 1500
  warmup_start_lr: 1.0e-6

model:
  type: PPMobileSeg
  num_classes: 150
  backbone:
    type: MobileSeg_Tiny
    inj_type: AAM
    out_feat_chs: [32, 64, 128]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/ade20k/pp_mobileseg_tiny/pretrain/model.pdparams
  upsample: intepolate  # During exportation, you need to change it to vim for using VIM

