_base_: './pp_mobileseg_base_ade20k_512x512_160k.yml'

model:
  type: PPMobileSeg
  num_classes: 150
  backbone:
    type: MobileSeg_Tiny
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/ade20k/pp_mobileseg_tiny/pretrain/model.pdparams
    out_channels: 256
    out_feat_chs: [32, 64, 128]
    stride_attention: True
  head_use_dw: True
  upsample: intepolate

