batch_size: 32    # total batch size: 32 * 2
iters: 46000

train_dataset:
  type: Dataset
  dataset_root: data/EG1800
  train_path: data/EG1800/train.txt
  num_classes: 2
  transforms:
    - type: Resize
      target_size: [224, 224]
    - type: ResizeStepScaling
      scale_step_size: 0
    - type: RandomRotation
    - type: RandomPaddingCrop
      crop_size: [224, 224]
    - type: RandomHorizontalFlip
    - type: RandomDistort
    - type: RandomBlur
      prob: 0.3
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: data/EG1800
  val_path: data/EG1800/val.txt
  num_classes: 2
  transforms:
    - type: Resize
      target_size: [224, 224]
    - type: Normalize
  mode: val

export:
  transforms:
    - type: Resize
      target_size: [224, 224]
    - type: Normalize

optimizer:
  type: adam
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.001
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
  coef: [1]

model:
  type: PortraitNet
  backbone:
    type: MobileNetV2_x1_0 # out channels: [24, 32, 96, 320]
    pretrained: https://paddleseg.bj.bcebos.com/dygraph/backbone/mobilenetv2_x1_0_ssld.tar.gz
  add_edge: False
  num_classes: 2
