batch_size: 128
iters: 10000
save_interval: 400

model:
  type: PPHumanSegLite
  pretrained: saved_model/pphumanseg_lite_imagenet_pretrain_humanseg/best_model/model.pdparams
  align_corners: False
  num_classes: 2

train_roots:
  - data/portrait14k
  - data/matting_human_half
  - data/humanseg

train_data_ratio:
  - 8
  - 1
  - 1

val_roots:
  - data/portrait14k
  - data/matting_human_half
  - data/humanseg

dataset_weights:
  - 0.4
  - 0.2
  - 0.4

class_weights:
  - 0.3
  - 0.7

train_transforms:
  - type: PaddingByAspectRatio
    aspect_ratio: 1.77777778
  - type: Resize
    target_size: [398, 224]
  - type: ResizeStepScaling
    scale_step_size: 0
  - type: RandomRotation
  - type: RandomPaddingCrop
    crop_size: [398, 224]
  - type: RandomHorizontalFlip
  - type: RandomDistort
  - type: RandomBlur
    prob: 0.3
  - type: Normalize

val_transforms:
  - type: PaddingByAspectRatio
    aspect_ratio: 1.77777778
  - type: Resize
    target_size: [398, 224]
  - type: Normalize

export:
  transforms:
    - type: Resize
      target_size: [398, 224]
    - type: Normalize

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.1
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: SemanticConnectivityLearning
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.05, 0.2]
  coef: [1]
