_base_: '../_base_/cityscapes.yml'

iters: 160000

model:
  type: DeepLabV3
  backbone:
    type: MobileNetV3_small_x1_0
    pretrained: Null
  num_classes: 19
  pretrained: Null
  backbone_indices: [0, 3]

optimizer:
  weight_decay: 0.00004
