_base_: '../_base_/cityscapes.yml'

batch_size: 1
iters: 160000

model:
  type: FCN
  backbone:
    type: SwinTransformer
    embed_dim: 128
    depths: [2, 2, 18, 2]
    num_heads: [4, 8, 16, 32]
    window_size: 7
    ape: False
    drop_path_rate: 0.3
    patch_norm: True
    pretrained: SwinTransformer_base_patch4_window7_224_pretrained.pdparams
    out_indices: [3]
  num_classes: 19

optimizer:
  weight_decay: 0.0001

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
