train_dataset:
  type: Dataset
  dataset_root: ../Swin-Transformer-Semantic-Segmentation/data/IDD_Segmentation
  train_path: ../Swin-Transformer-Semantic-Segmentation/data/IDD_Segmentation/train.txt
  num_classes: 26
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: ../Swin-Transformer-Semantic-Segmentation/data/IDD_Segmentation
  val_path: ../Swin-Transformer-Semantic-Segmentation/data/IDD_Segmentation/val.txt
  num_classes: 26
  transforms:
    - type: Resize
      target_size: [1920, 1080]
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  mode: val


model:
  type: MLAHead
  backbone:
    type: SwinTransformer
    embed_dim: 128
    depths: [2, 2, 18, 2]
    num_heads: [4, 8, 16, 32]
    window_size: 7
    ape: False
    drop_path_rate: 0.3
    patch_norm: True
  num_classes: 26
  in_channels: [128, 256, 512, 1024]
  mlahead_channels: 128

optimizer:
  weight_decay: 0.0

lr_scheduler:
  end_lr: 1.0e-4

iters: 40000

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
