_base_: '../_base_/autonue.yml'

model:
  type: MLATransformer
  backbone:
    type: SwinTransformer_base_patch4_window7_224
    ape: False
    drop_path_rate: 0.3
    patch_norm: True
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/swin_transformer_base_patch4_window7_224_imagenet_1k.tar.gz
  num_classes: 26
  in_channels: [128, 256, 512, 1024]
  mlahead_channels: 128

iters: 160000

loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1, 0.4]
