language: python

python:
  - '3.6'

env:
  - PYTHONPATH=${PWD}

install:
  - pip install --upgrade paddlepaddle
  - pip install -r requirements.txt

script:
  - python -c 'import paddleseg'

notifications:
  email:
    on_success: change
    on_failure: always
