language: python

python:
  - '3.6'

env:
  - PYTHONPATH=${PWD}

install:
  - pip install --upgrade paddlepaddle
  - pip install -r requirements.txt

script:
  - /bin/bash legacy/test/ci/check_code_style.sh

notifications:
  email:
    on_success: change
    on_failure: always
