_base_: '../_base_/cityscapes.yml'

batch_size: 4
iters: 200000

train_dataset:
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1536, 768]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

val_dataset:
  transforms:
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 0.0005

loss:
  types:
    - type: OhemCrossEntropyLoss
      thresh: 0.7
      min_kept: 10000
  coef: [1]

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0.0
  power: 0.9

model:
  type: LPSNet
  in_channels: 3
  depths: [1, 3, 3, 10, 10]
  channels: [8, 24, 48, 96, 96]
  scale_ratios: [1, 0.25]
  pretrained: https://paddleseg.bj.bcebos.com/dygraph/cityscapes/lpsnet_m_cityscapes_1536x1024_200k/lpsnet_m_pretrained_imagenet.zip
  num_classes: 19