batch_size: 4
iters: 320000

train_dataset:
  type: Tusimple
  dataset_root: ./data/tusimple
  cut_height: 160
  transforms:
    - type: CutHeight
      cut_height: 160
    - type: LaneRandomRotation
    - type: RandomHorizontalFlip
    - type: Resize
      target_size: [640, 368]
    - type: RandomDistort
      brightness_range: 0.25
      brightness_prob: 1
      contrast_range: 0.25
      contrast_prob: 1
      saturation_range: 0.25
      saturation_prob: 1
      hue_range: 63
      hue_prob: 1
    - type: Normalize
  mode: train

val_dataset:
  type: Tusimple
  dataset_root: ./data/tusimple
  cut_height: 160
  transforms:
    - type: CutHeight
      cut_height: 160
    - type: Resize
      target_size: [640, 368]
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: LaneCrossEntropyLoss
  coef: [1]

model:
  type: BiSeNetLane
  pretrained: Null
