batch_size: 1
iters: 520625

model:
    type: MscaleOCR
    num_classes: 19
    backbone: HRNETV2PSA

loss:
  types:
    - type: RMILoss
    - type: RMILoss
    - type: RMILoss
    - type: RMILoss
  coef: [1, 0.4, 0.05, 0.05]

lr_scheduler:
  type: LambdalDecay
  learning_rate: 0.005
  lr_lambda: 'lambda iter: (1-math.ceil(iter/2975)/175)**2)'
