_base_: '../_base_/cityscapes.yml'

batch_size: 1
iters: 520000

model:
    type: PSA
    num_classes: 19
    backbone: 
      type: HRNETV2_PSA

loss:
  types:
    - type: RMILoss
    - type: RMILoss
    - type: RMILoss
    - type: RMILoss
  coef: [1, 0.4, 0.05, 0.05]

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.005
  end_lr: 0.0
  power: 0.9