batch_size: 1
iters: 520000

train_dataset:
  type: Cityscapes
  dataset_root: data/cityscapes
  transforms:
    - type: RandomPaddingCrop
      crop_size: [1024, 2048]
    - type: RandomHorizontalFlip
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: data/cityscapes
  transforms:
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  mode: val

model:
    type: PSANet
    num_classes: 19
    backbone: 
      type: HRNETV2_PSA
      pretrained: pretrained/hrnetv2_w48_imagenet_pretrained.pdparams

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 1.0e-4

lr_scheduler:
  type: LambdaDecay
  learning_rate: 0.005
  lr_lambda_params:
    max_epoch: 175
    power: 2.0
    len_train_dataset: 2975

loss:
  types:
    - type: RMILoss
    - type: RMILoss
    - type: RMILoss
    - type: RMILoss
  coef: [1, 0.4, 0.05, 0.05]
