data_root: test_tipc/data
batch_size: 6
iters: 20
train_dataset:
  type: LungCoronavirus
  dataset_root: mini_lung_coronavirus
  result_dir: test_tipc/data/mini_lung_coronavirus
  num_classes: 3
  transforms:
    - type: RandomResizedCrop3D
      size: 128
      scale: [0.8, 1.2]
    - type: RandomRotation3D
      degrees: 90
    - type: RandomFlip3D
  mode: train


val_dataset:
  type: LungCoronavirus
  dataset_root: mini_lung_coronavirus
  result_dir: test_tipc/data/mini_lung_coronavirus
  num_classes: 4
  transforms: []
  mode: val
  dataset_json_path: "test_tipc/data/mini_lung_coronavirus/dataset.json"


test_dataset:
  type: LungCoronavirus
  dataset_root: mini_lung_coronavirus
  result_dir: test_tipc/data/mini_lung_coronavirus
  num_classes: 4
  transforms: []
  mode: test
  dataset_json_path: "test_tipc/data/mini_lung_coronavirus/dataset.json"

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 1.0e-4

lr_scheduler:
  type: PolynomialDecay
  decay_steps: 20
  learning_rate: 0.001
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
          weight: Null
        - type: DiceLoss
      coef: [1, 1]
  coef: [1]


model:
  type: VNet
  elu: False
  in_channels: 1
  num_classes: 3
  pretrained: Null
