repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: no-commit-to-branch
        args: [--branch, stable]
    -   id: check-added-large-files
        args: [--maxkb=16]
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: check-xml
    -   id: check-toml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: mixed-line-ending
        args: [--fix=lf ]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: pretty-format-json
        args: [--autofix, --indent=4, --no-ensure-ascii]

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
