batch_size: 1
iters: 20

train_dataset:
  type: Cityscapes
  dataset_root: test_tipc/data/cityscapes/
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0
    - type: RandomPaddingCrop
      crop_size: [2048, 1024]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.25
      brightness_prob: 1
      contrast_range: 0.25
      contrast_prob: 1
      saturation_range: 0.25
      saturation_prob: 1
      hue_range: 63
      hue_prob: 1
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: test_tipc/data/cityscapes
  transforms:
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  mode: val

model:
    type: PSANet
    num_classes: 19
    backbone: 
      type: HRNETV2_PSA

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 1.0e-4

lr_scheduler:
  type: LambdaDecay
  learning_rate: 0.005
  lr_lambda_params:
    max_epoch: 175
    power: 2.0
    len_train_dataset: 2975

loss:
  types:
    - type: RMILoss
      do_rmi: False
    - type: RMILoss
      do_rmi: True
    - type: RMILoss
      do_rmi: False
    - type: RMILoss
      do_rmi: False
  coef: [1, 0.4, 0.05, 0.05]
