_base_: '../_base_/vaihingen.yml'

loss:
  types:
    - type: CrossEntropyLoss
    - type: PixelContrastCrossEntropyLoss
      temperature: 0.1
      base_temperature: 0.07
      ignore_index: 255
      max_samples: 1024
      max_views: 100
  coef: [1, 0.1]

model:
  type: HRNetW48Contrast
  backbone:
    type: HRNet_W48
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
  num_classes: 6
  in_channels: 720
  drop_prob: 0.1
  proj_dim: 720