_base_: '../_base_/isaid_512x512.yml'

model:
  type: C2FNet
  backbone:
    type: HRNet_W18
    align_corners: False
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  num_classes: 16
  pretrained: Null
  backbone_indices: [-1]

coase_model:
  type: FCN
  backbone:
    type: HRNet_W18
    align_corners: False
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  num_classes: 16
  pretrained: Null
  backbone_indices: [-1]
