_base_: './base_cfg.yml'

model:
  type: BiSeNetV2

loss:
  types:
    - type: MixedLoss
      losses:
        - type: OhemCrossEntropyLoss
          min_kept: 65000
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
  coef: [1, 1, 1, 1, 1]