_base_: './base_cfg.yml'

model:
  type: OCRNet
  backbone:
    type: HRNet_W18
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  backbone_indices: [0]

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 65000
    - type: LovaszSoftmaxLoss
  coef: [0.8, 0.2, 0.32, 0.08]
  repeat: 2