_base_: '../_base_/isaid.yml'

train_dataset:
  type: Dataset
  dataset_root: data/iSAID
  train_path: data/iSAID/train.txt
  num_classes: 16
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 0.4]

model:
  type: PSPNet
  backbone:
    type: ResNet50_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  num_classes: 16
  enable_auxiliary_loss: True
  align_corners: False
  pretrained: null
