_base_: '../_base_/vaihingen.yml'

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 0.4]

model:
  type: PSPNet
  backbone:
    type: ResNet50_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  num_classes: 6
  enable_auxiliary_loss: True
  align_corners: False
  pretrained: null