batch_size: 1
iters: 80000

train_dataset:
  type: Dataset
  dataset_root: data/seg_jishui_dataset
  num_classes: 2
  mode: train
  train_path: data/seg_jishui_dataset/train_merged.txt
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 1024]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize


val_dataset:
  type: Dataset
  dataset_root: data/seg_jishui_dataset
  num_classes: 2
  mode: val
  val_path: data/seg_jishui_dataset/test.txt
  transforms:
    - type: Normalize

optimizer:
  type: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.00006
  power: 1

loss:
  types:
    - type: DiceLoss
  coef: [1]

model:
  type: SegFormer_B2
  num_classes: 2
  pretrained: https://bj.bcebos.com/paddleseg/dygraph/mix_vision_transformer_b2.tar.gz

#test_config:
#  is_slide: True
#  crop_size: [1024, 1024]
#  stride: [768, 768]
