batch_size: 16
iters: 50000

train_dataset:
  type: HybridDataset
  dataset_root: data/hybrid_data
  train_file: train.txt
  transforms:
    - type: RandomCropByAlpha
      crop_size: [[640, 640], [960, 960], [1280, 1280]]
    - type: RandomHorizontalFlip
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    - type: Resize
      target_size: [320, 320]
  mode: train

val_dataset:
  type: AIM500
  dataset_root: data/aim500
  val_file: val.txt
  transforms:
    - type: HybridResize
      if_hybrid: True
      global_ratio: 0.25
      local_ratio: 0.5
      max_size: [1600, 1600]
  mode: val
  get_trimap: True

model:
  type: AIM
#   backbone:
#     type: ResNet34_mp
#     pretrained: https://paddleseg.bj.bcebos.com/matting/models/xxxxx/model.pdparams
  pretrained: Null

lr_scheduler:
    type: PolynomialDecay
    learning_rate: 0.000001

optimizer:
  type: adam
  weight_decay: 0.0
