Global:
  reader_config: configs/datasets/cityscapes_1024x512_scale1.0.yml
  model_dir: ./liteseg_tiny_scale1.0
  model_filename: model.pdmodel
  params_filename: params.pdiparams

TrainConfig:
 epochs: 14
 eval_iter: 90
 learning_rate: 
   type: PiecewiseDecay
   boundaries: [900]
   values: [0.001, 0.0005]
 optimizer_builder:
   optimizer: 
     type: SGD
   weight_decay: 0.0005  
