global:
  device: gpu         # ['cpu', 'gpu', 'xpu', 'npu', 'mlu']
  save_dir: ./output
  seed: null
  num_workers: 0
  precision: fp32     # [fp32, fp16]
  amp_level: O1       # [O1, O2]
  data_format: NCHW   # [NCHW, NHWC]

train:
  batch_size: 2
  iters: 1000
  save_interval: 1000
  keep_checkpoint_max: 5
  resume_model: null
  do_eval: false
  use_vdl: false
  log_iters: 10
  repeats: 1
  profiler_options: null
  to_static_training: false

test:
  is_aug: false
  scales: [1.0]
  flip_horizontal: false
  flip_vertical: false
  is_slide: false
  crop_size: [512, 512]
  stride: [512, 512]

train_dataset:
  type: Dataset
  dataset_root: data/optic_disc_seg
  train_path: data/optic_disc_seg/train_list.txt
  num_classes: 2
  mode: train
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: data/optic_disc_seg
  val_path: data/optic_disc_seg/val_list.txt
  num_classes: 2
  mode: val
  transforms:
    - type: Normalize

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 1, 1]


model:
  type: PPLiteSeg
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz
