_base_: '../_base_/vaihingen.yml'

loss:
  types:
    - type: CrossEntropyLoss
  types:
    - type: CrossEntropyLoss
  coef: [1, 0.4]

model:
  type: UPerNet
  backbone:
    type: ResNet50_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  num_classes: 6
  backbone_indices: [0, 1, 2, 3]
  channels: 512
  dropout_prob: 0.1
  enable_auxiliary_loss: True