_base_: '../_base_/global_configs.yml'

train_dataset:
  type: Abdomen
  dataset_root: abdomen/abdomen_phase0
  result_dir: abdomen/abdomen_phase1
  transforms:
    - type: RandomFlip3D
      flip_axis: [1, 2]
    - type: RandomQuarterTurn3D
      rotate_planes: [[ 1, 2 ]]
    - type: RandomRotation3D
      degrees: 20
      rotate_planes: [[1, 2]]
    - type: Resize3D
      size: [1, 224, 224]
  mode: train
  num_classes: 9

val_dataset:
  type: Abdomen
  dataset_root: abdomen/abdomen_phase0
  result_dir: abdomen/abdomen_phase1
  num_classes: 9
  transforms:
    - type: Resize3D
      size: [1, 224, 224]
  mode: val
  dataset_json_path: data/abdomen/abdomen_raw/dataset.json

test_dataset:
  type: Abdomen
  dataset_root:  abdomen/abdomen_phase0
  result_dir:  abdomen/abdomen_phase1
  num_classes: 9
  transforms:
    - type: Resize3D
      size: [1, 224, 224]
  mode: val
  dataset_json_path: data/abdomen/abdomen_raw/dataset.json
