EVAL_CROP_SIZE: (2048, 1024) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (1024, 512) # (width, height), for unpadding rangescaling and stepscaling
AUG:
#    AUG_METHOD: "unpadding" # choice unpadding rangescaling and stepscaling
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (1024, 512) # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
BATCH_SIZE: 8

DATASET:
    DATA_DIR: "./dataset/cityscapes/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 19
    TEST_FILE_LIST: "./dataset/cityscapes/val.list"
    TRAIN_FILE_LIST: "./dataset/cityscapes/train.list"
    VAL_FILE_LIST: "./dataset/cityscapes/val.list"
    IGNORE_INDEX: 255
    SEPARATOR: " "

MODEL:
    MODEL_NAME: "hrnet"
    DEFAULT_NORM_TYPE: "bn"
    HRNET:
        STAGE2:
            NUM_CHANNELS: [18, 36]
        STAGE3:
            NUM_CHANNELS: [18, 36, 72]
        STAGE4:
            NUM_CHANNELS: [18, 36, 72, 144]
        BIAS: False
        ALIGN_CORNERS: False

TRAIN:
    PRETRAINED_MODEL_DIR: u"./pretrained_model/hrnet_w18_ssld"
    MODEL_SAVE_DIR: "output/hrnetw18_bn_cityscapes"
    SNAPSHOT_EPOCH: 10
    SYNC_BATCH_NORM: True

TEST:
    TEST_MODEL: "output/hrnetw18_bn_cityscapes/best_model"

SOLVER:
    LR: 0.01
    LR_POLICY: "poly"
    WEIGHT_DECAY: 5.0e-4
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 215
