batch_size: 1
iters: 40000

model:
  type: MscaleOCRNet
  n_scales: [0.5,1.0]
  backbone:
    type: HRNet_W48
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
  num_classes: 19
  backbone_indices: [0]

train_dataset:
  type: Cityscapes
  dataset_root: ../../dataset/cityscapes-for-nvidia
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
#       crop_size: [300, 300]
#     - type: RandomHorizontalFlip
#     - type: RandomDistort
#       brightness_range: 0.4
#       contrast_range: 0.4
#       saturation_range: 0.4
    - type: Normalize
  mode: train


val_dataset:
  type: Cityscapes
  dataset_root: ../../dataset/cityscapes-for-nvidia
  transforms:
    - type: Normalize
  mode: val

optimizer:
  type: sgd

learning_rate:
  value: 0.01
  decay:
    type: poly
    power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
#   coef: [1, 0.4, 0.05, 0.05]
  coef: [1, 0, 0.05, 0.05]
