batch_size: 1
iters: 65078

model:
  type: MscaleOCRNet
  n_scales: [0.5,1.0,2.0]
  backbone:
    type: HRNet_W48
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
  num_classes: 19
  backbone_indices: [0]

train_dataset:
  type: CityscapesAutolabeling
  dataset_root: ../../dataset/cityscapes-for-nvidia
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0
    - type: RandomPaddingCrop
      crop_size: [2048, 1024]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.25
      brightness_prob: 1
      contrast_range: 0.25
      contrast_prob: 1
      saturation_range: 0.25
      saturation_prob: 1
      hue_range: 63
      hue_prob: 1
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  mode: train


val_dataset:
  type: CityscapesAutolabeling
  dataset_root: ../../dataset/cityscapes-for-nvidia
  transforms:
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0001

learning_rate:
  value: 0.01  # right
  decay:
    type: poly
    power: 2
    end_lr: 0.0

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 0.4, 0.05, 0.05]
