_base_: '../_base_/cityscapes.yml'

batch_size: 2
iters: 40000

model:
  type: OCRNet
  backbone:
    type: HRNet_W18
  num_classes: 19
  backbone_channels: [270]
  backbone_pretrained: pretrained_model/hrnet_w18_imagenet
  model_pretrained: None
