_base_: 'seaformer_base_ade20k_512x512_160k.yml'

model:
  type: SeaFormerSeg
  backbone: 
    type: SeaFormer_small
    pretrained: pretrained/seaformer_small.pdparams
  num_classes: 150
  head_channels: 128
  embed_dims: [96, 128]
  is_dw: True
  dropout_ratio: 0.1
  align_corners: False
  input_transform: 'multiple_select'