_base_: 'seaformer_base_ade20k_512x512_160k.yml'

model:
  type: SeaFormerSeg
  backbone: 
    type: SeaFormer_large
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/ade20k/backbone/seaformer_large_imagenet_pretrained.pdparams
  num_classes: 150
  head_channels: 192
  embed_dims: [128, 160, 192]
  in_index: [0, 1, 2, 3]