EVAL_CROP_SIZE: (2049, 1025) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (769, 769) # (width, height), for unpadding rangescaling and stepscaling
AUG:
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
BATCH_SIZE: 32
DATASET:
    DATA_DIR: "./dataset/cityscapes/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 19
    TEST_FILE_LIST: "dataset/cityscapes/val.list"
    TRAIN_FILE_LIST: "dataset/cityscapes/train.list"
    VAL_FILE_LIST: "dataset/cityscapes/val.list"
    VIS_FILE_LIST: "dataset/cityscapes/val.list"
    IGNORE_INDEX: 255
    SEPARATOR: " "
FREEZE:
    MODEL_FILENAME: "model"
    PARAMS_FILENAME: "params"
MODEL:
    DEFAULT_NORM_TYPE: "bn"
    MODEL_NAME: "deeplabv3p"
    DEEPLAB:
        BACKBONE: "mobilenetv3_large"
        ASPP_WITH_SEP_CONV: True
        DECODER_USE_SEP_CONV: True
        ENCODER_WITH_ASPP: True
        ENABLE_DECODER: True
        OUTPUT_STRIDE: 32
        BACKBONE_LR_MULT_LIST: [0.15,0.35,0.65,0.85,1]
        ENCODER:
            POOLING_STRIDE: (4, 5)
            POOLING_CROP_SIZE: (769, 769)
            ASPP_WITH_SE: True
            SE_USE_QSIGMOID: True
            ASPP_CONVS_FILTERS: 128
            ASPP_WITH_CONCAT_PROJECTION: False
            ADD_IMAGE_LEVEL_FEATURE: False
        DECODER:
            USE_SUM_MERGE: True
            CONV_FILTERS: 19
            OUTPUT_IS_LOGITS: True

TRAIN:
    PRETRAINED_MODEL_DIR: u"pretrained_model/mobilenetv3-1-0_large_bn_imagenet"
    MODEL_SAVE_DIR: "saved_model/deeplabv3p_mobilenetv3_large_cityscapes"
    SNAPSHOT_EPOCH: 1
    SYNC_BATCH_NORM: True
TEST:
    TEST_MODEL: "saved_model/deeplabv3p_mobilenetv3_large_cityscapes/final"
SOLVER:
    LR: 0.2
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 850
