TRAIN_CROP_SIZE: (500, 500) # (width, height), for unpadding rangescaling and stepscaling  #训练时图像裁剪尺寸（宽，高）
EVAL_CROP_SIZE: (500, 500) # (width, height), for unpadding rangescaling and stepscaling  #验证时图像裁剪尺寸（宽，高）
AUG:
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (500, 500) # (width, height), for unpadding

    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling

    MAX_SCALE_FACTOR: 1.25  # for stepscaling
    MIN_SCALE_FACTOR: 0.75  # for stepscaling
    SCALE_STEP_SIZE: 0.05  # for stepscaling
    MIRROR: True
    FLIP: True
BATCH_SIZE: 16  #批处理大小
DATASET:
    DATA_DIR: "./dataset/VOCtrainval_11-May-2012/VOC2012/"  #图片路径
    IMAGE_TYPE: "rgb"  # choice rgb or rgba  #图片类别“RGB”
    NUM_CLASSES: 21  #类别数（包括背景类别）
    TEST_FILE_LIST: "dataset/VOCtrainval_11-May-2012/VOC2012/ImageSets/Segmentation/val.list"
    TRAIN_FILE_LIST: "dataset/VOCtrainval_11-May-2012/VOC2012/ImageSets/Segmentation/train.list"
    VAL_FILE_LIST: "dataset/VOCtrainval_11-May-2012/VOC2012/ImageSets/Segmentation/val.list"
    VIS_FILE_LIST: "dataset/VOCtrainval_11-May-2012/VOC2012/ImageSets/Segmentation/val.list"
    IGNORE_INDEX: 255
    SEPARATOR: " "
MODEL:
    MODEL_NAME: "deeplabv3p"
    DEFAULT_NORM_TYPE: "bn"  #指定norm的类型，此处提供bn和gn（默认）两种选择，分别指batch norm和group norm。
    DEEPLAB:
        BACKBONE: "mobilenetv2"
        DEPTH_MULTIPLIER: 1.0
        ENCODER_WITH_ASPP: False
        ENABLE_DECODER: False
TRAIN:
    PRETRAINED_MODEL_DIR: "./pretrained_model/deeplabv3p_mobilenetv2-1-0_bn_coco/"
    MODEL_SAVE_DIR: "./saved_model/lovasz-softmax-voc"  #模型保存路径
    SNAPSHOT_EPOCH: 10
TEST:
    TEST_MODEL: "./saved_model/lovasz-softmax-voc/final"  #为测试模型路径
SOLVER:
    NUM_EPOCHS: 100  #训练epoch数，正整数
    LR: 0.0001  #初始学习率
    LR_POLICY: "poly"  #学习率下降方法, 选项为poly、piecewise和cosine
    OPTIMIZER: "sgd" #优化算法, 选项为sgd和adam
    LOSS: ["lovasz_softmax_loss","softmax_loss"]
    LOSS_WEIGHT:
        LOVASZ_SOFTMAX_LOSS: 0.2
        SOFTMAX_LOSS: 0.8
