_base_: '../_base_/cityscapes.yml'

batch_size: 12
iters: 80000

model:
  type: STDCSeg_1 # base: STDCSeg_1
  backbone:
    # STDC_pp_1:ruturns some features, STDC_pp_1_s4_ch_512: The channel of last stage is 512
    # STDC_pp_2:returns all features,
    type: STDC_pp_1
    block_type: cat # base cat
    pretrained: pretrained_model/stdc1net_class_pretrained_cat_pp.pdparams
    atten_type: AttenNone # base: AttenNone
  # ContextPath_1: base, process some features, ContextPath_1_1: arm block self contained
  # ContextPath_2:process all features
  cpp_type: ContextPath_1
  arm_type: ARM_14_3
  resize_mode: nearest  # base: nearest, support:nearest and bilinear
  out_seg_head_ch: 256  # base: 256, support: 64, 128, 256

loss:
  types:
    - type: OhemCrossEntropyLoss
    - type: OhemCrossEntropyLoss
    - type: OhemCrossEntropyLoss
    - type: DetailAggregateLoss
  coef: [1, 1, 1, 1]
