_base_: '../_base_/ade20k.yml'

batch_size: 8   # total: 16
iters: 160000

optimizer:
  weight_decay: 5.0e-4  # 4.0e-5 or 5.0e-4

lr_scheduler:
  warmup_iters: 1000
  warmup_start_lr: 1.0e-5

model:
  type: STDCSeg
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/STDCNet2.tar.gz
  pretrained: null

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 65000  # batch_size * 512 * 512 // 16
    - type: OhemCrossEntropyLoss
      min_kept: 65000
    - type: OhemCrossEntropyLoss
      min_kept: 65000
    - type: DetailAggregateLoss
  coef: [1, 1, 1, 1]

val_dataset:
  transforms:
    - type: ResizeByShort
      short_size: 512
    - type: Normalize
