_base_: 'mri_spine_seg_1e-2_big_rmresizecrop.yml'

model:
  type: VNet
  elu: False
  in_channels: 1
  num_classes: 3
  pretrained: null
  kernel_size: [[2,2,4], [2,2,2], [2,2,2], [2,2,2]]
  stride_size: [[2,2,1], [2,2,1], [2,2,2], [2,2,2]]
