_base_: 'lvjian1_1024x1024.yml'

batch_size: 2  # total: 2*4
iters: 40000   # 4w * 8 / 0.76w = 42 epoch

model:
  type: DeepLabV3P
  backbone:
    type: ResNet50_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null

lr_scheduler:
  learning_rate: 0.01

loss:
  types:
    - type: CrossEntropyLoss
      weight: [1, 10]
    #- type: OhemCrossEntropyLoss
    #  min_kept: 65000   # batch_size * w * h // 16
    #- type: FocalLoss
    #  alpha: 0.9
  coef: [1]
