_base_: './dwcoa.yml'

lr_scheduler:
  learning_rate: 0.01

model:
  type: BiSeNetV2

loss:
  types:
    #- type: CrossEntropyLoss
    #- type: DiceLoss
    - type: OhemCrossEntropyLoss
      min_kept: 65000
  coef: [1, 1, 1, 1, 1]

# loss:
#   types:
#     - type: MixedLoss
#       losses:
#         - type: OhemCrossEntropyLoss
#           min_kept: 65000
#         - type: LovaszSoftmaxLoss
#       coef: [0.8, 0.2]
#   coef: [1, 1, 1, 1, 1]