_base_: './dwcoa.yml'

batch_size: 4
iters: 40000

lr_scheduler:
  learning_rate: 0.01

model:
  type: OCRNet
  backbone:
    type: HRNet_W18
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  backbone_indices: [0]

loss:
  types:
    #- type: CrossEntropyLoss
    - type: OhemCrossEntropyLoss
      min_kept: 65000
    #- type: DiceLoss
  coef: [1, 0.4]
