_base_: 'lvjian1_1024x1024.yml'

batch_size: 2  # total: 2*4
iters: 40000   # 4w * 8 / 0.76w = 42 epoch

model:
  type: PPLiteSeg
  backbone:
    type: STDC1
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
  arm_out_chs: [32, 64, 128]
  seg_head_inter_chs: [32, 64, 64]

lr_scheduler:
  learning_rate: 0.01

loss:
  types:
    - type: CrossEntropyLoss
      weight: [1, 10]
    #- type: OhemCrossEntropyLoss
    #  min_kept: 65000   # batch_size * w * h // 16
    #- type: FocalLoss
    #  alpha: 0.9
  coef: [1, 1, 1]
