_base_: 'lvjian1_1024x1024.yml'

batch_size: 4  # total: 4*4
iters: 40000   # 4w * 16 / 0.76w = 84 epoch

model:
  type: OCRNet
  backbone:
    type: HRNet_W18
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  backbone_indices: [0]

lr_scheduler:
  learning_rate: 0.01

loss:
  types:
    - type: CrossEntropyLoss
      weight: [1, 10]
    #- type: OhemCrossEntropyLoss
    #  min_kept: 65000   # batch_size * w * h // 16
    #- type: FocalLoss
    #  alpha: 0.9
  coef: [1, 0.4]
