_base_: './tesla.yml'

batch_size: 4
iters: 80000

lr_scheduler:
  learning_rate: 0.01

model:
  type: BiSeNetV2

loss:
  types:
    #- type: CrossEntropyLoss
    #  weight: [1, 10]
    - type: OhemCrossEntropyLoss
      min_kept: 65000   # batch_size * w * h // 16
  coef: [1, 1, 1, 1, 1]
