_base_: './tesla.yml'

batch_size: 4
iters: 80000

lr_scheduler:
  learning_rate: 0.01

model:
  type: SFNet
  backbone:
    type: ResNet18_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet18_vd_ssld_v2.tar.gz
  backbone_indices: [0, 1, 2, 3]

loss:
  types:
    #- type: CrossEntropyLoss
    #  weight: [1, 10]
    - type: OhemCrossEntropyLoss
      min_kept: 65000   # batch_size * w * h // 16
  coef: [1]
