batch_size: 4
iters: 80000

train_dataset:
  type: Dataset
  dataset_root: data/Potsdam
  train_path: data/Potsdam/train.txt
  num_classes: 6
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:  
  type: Dataset 
  dataset_root: data/Potsdam 
  val_path: data/Potsdam/val.txt 
  num_classes: 6  
  mode: val 
  transforms: 
    - type: Normalize 

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]