_base_: '../_base_/ade20k.yml'
batch_size: 4
iters: 150000

loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1, 0.4]


model:
  type: GINet
  num_classes: 150
  backbone:
    type: ResNet101_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet101_vd_ssld.tar.gz
  aux: True
  se_loss: False
  sc_loss: False
  backbone_indices: [0, 1, 2, 3]
  jpu: True
  base_size: 520
  crop_size: 480
  mean: [.485, .456, .406]
  std: [.229, .224, .225]


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5


lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.005
  end_lr: 0
  power: 0.9
