batch_size: 2
iters: 80000

train_dataset_src:
  type: GTA5
  dataset_root: data/GTA5
  transforms:
    - type: RandomVerticalFlip
      prob: 0.5
    - type: Resize
      target_size: [1280, 720]
      interp: CUBIC
    - type: RandomHorizontalFlip
    - type: RandomBlur
      prob: 0.5
    - type: Normalize
  mode: train

train_dataset_tgt:
  type: Cityscapes
  dataset_root: data/cityscapes
  transforms:
    - type: RandomVerticalFlip
      prob: 0.5
    - type: Resize
      target_size: [1280, 720]
      interp: CUBIC
    - type: RandomHorizontalFlip
    - type: RandomBlur
      prob: 0.5
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: data/cityscapes
  transforms:
    - type: Normalize
  mode: val

model:
  type: DeepLabV2
  backbone:
    type: ResNet101
  num_classes: 19
  backbone_indices: [0, 1]
  align_corners: True
  pretrained: models/torch_transfer_gta5source.pdparams  # gta5 source/ others get from model

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 5.0e-4

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 1e-4
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss # aug
    - type: AugLoss
  coef: [1, 0.1]
