_base_: '../_base_/cityscapes_1024x1024.yml'

batch_size: 4
iters: 160000

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1.0, 0.4]

learning_rate:
  value: 0.05
  decay:
    type: poly
    power: 0.9
    end_lr: 1.0e-4

model:
  type: FastSCNN
  num_classes: 19
  enable_auxiliary_loss: True
  pretrained: null
