_base_: '../_base_/cityscapes.yml'

batch_size: 4  # total batch size is 16
iters: 160000

train_dataset:
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

val_dataset:
  transforms:
    - type: Resize
      target_size: [2048, 1024]
      keep_ratio: True
      size_divisor: 32
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

export:
  transforms:
    - type: Resize
      target_size: [2048, 1024]
      keep_ratio: True
      size_divisor: 32
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

optimizer:
  _inherited_: False
  type: AdamW
  weight_decay: 4.0e-5 # 0.01

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01 #0.0012
  end_lr: 0
  power: 0.9 # 1.0
  warmup_iters: 1500
  warmup_start_lr: 1.0e-6

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

model:
  type: TopFormer
  num_classes: 19
  backbone:
    type: TopTransformer_Base
    lr_mult: 0.1
    pretrained: https://paddleseg.bj.bcebos.com/dygraph/backbone/topformer_base_imagenet_pretrained.zip



# batch_size: 4
# export:
#   transforms:
#   - keep_ratio: true
#     size_divisor: 32
#     target_size:
#     - 2048
#     - 512
#     type: Resize
#   - mean:
#     - 0.485
#     - 0.456
#     - 0.406
#     std:
#     - 0.229
#     - 0.224
#     - 0.225
#     type: Normalize
# iters: 160000
# loss:
#   coef:
#   - 1
#   types:
#   - ignore_index: 255
#     type: CrossEntropyLoss
# lr_scheduler:
#   end_lr: 0
#   learning_rate: 0.0012
#   power: 1.0
#   type: PolynomialDecay
#   warmup_iters: 1500
#   warmup_start_lr: 1.0e-06
# model:
#   backbone:
#     in_channels: 3
#     lr_mult: 0.1
#     pretrained: https://paddleseg.bj.bcebos.com/dygraph/backbone/topformer_base_imagenet_pretrained.zip
#     type: TopTransformer_Base
#   num_classes: 19
#   type: TopFormer
# optimizer:
#   type: AdamW
#   weight_decay: 0.01
# train_dataset:
#   dataset_root: data/cityscapes
#   mode: train
#   transforms:
#   - max_scale_factor: 2.0
#     min_scale_factor: 0.5
#     scale_step_size: 0.25
#     type: ResizeStepScaling
#   - crop_size:
#     - 1024
#     - 512
#     type: RandomPaddingCrop
#   - type: RandomHorizontalFlip
#   - brightness_range: 0.4
#     contrast_range: 0.4
#     saturation_range: 0.4
#     type: RandomDistort
#   - mean:
#     - 0.485
#     - 0.456
#     - 0.406
#     std:
#     - 0.229
#     - 0.224
#     - 0.225
#     type: Normalize
#   type: Cityscapes
# val_dataset:
#   dataset_root: data/cityscapes
#   mode: val
#   transforms:
#   - keep_ratio: true
#     size_divisor: 32
#     target_size:
#     - 2048
#     - 1024
#     type: Resize
#   - mean:
#     - 0.485
#     - 0.456
#     - 0.406
#     std:
#     - 0.229
#     - 0.224
#     - 0.225
#     type: Normalize
#   type: Cityscapes