_base_: '../_base_/ade20k.yml'

batch_size: 8  # total is 16
iters: 160000

optimizer:
  _inherited_: False
  type: adam
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.00012
  end_lr: 0
  power: 1.0
  warmup_iters: 1500
  warmup_start_lr: 1.0e-6

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

model:
  type: TopFormer
  backbone:
    type: TopTransformer_Tiny
    pretrained: pretrained_model/topformer_small.pdparams