
model:
  type: PPHumanSegLite
  align_corners: False
  num_classes: 2

export:
  transforms:
    - type: Resize
      target_size: [398, 224]
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: data/mini_supervisely
  val_path: data/mini_supervisely/val.txt
  num_classes: 2
  transforms:
    - type: Resize
      target_size: [398, 224]
    - type: Normalize
  mode: val
