_base_: '../_base_/pascal_voc12aug.yml'

model:
  type: FCN
  backbone:
    type: HRNet_W18
    align_corners: False
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  num_classes: 21
  pretrained: Null
  backbone_indices: [-1]

optimizer:
  weight_decay: 0.0005
