_base_: '../_base_/cityscapes.yml'

batch_size: 2   # total: 8
iters: 80000

model:
  type: FCN_8s
  arm_type: ARM_18_1
  backbone:
    type: ResNet18_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet18_vd_ssld_v2.tar.gz
  backbone_indices: [-1, -2, -3]

optimizer:
  weight_decay: 0.0005
