_base_: './pp_liteseg_stdc1net_camvid_960x720_bs24_10k.yml'

val_dataset:
  val_path: data/camvid/test.txt

model:
  _inherited_: False  # no inherit the model params from the base yaml
  type: PPLiteSeg
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz
