metric: COCO
num_classes: 5

TrainDataset:
  name: COCODataSet
  anno_path: ./dataset/MT_dataset/train.json
  dataset_dir: ./
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']
  allow_empty: true

EvalDataset:
  name: COCODataSet
  anno_path: ./dataset/MT_dataset/val.json
  dataset_dir: ./
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: ./dataset/MT_dataset/val.json # also support txt (like VOC's label_list.txt)
  dataset_dir: ./ # if set, anno_path will be 'dataset_dir/anno_path'
