EVAL_CROP_SIZE: (1025, 1025) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (769, 769) # (width, height), for unpadding rangescaling and stepscaling
AUG: 
    AUG_METHOD: u"stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (640, 640) # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
BATCH_SIZE: 8 
DATASET: 
    DATA_DIR: "./dataset/MiniDeepGlobeRoadExtraction/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 2
    TEST_FILE_LIST: "dataset/MiniDeepGlobeRoadExtraction/val.txt"
    TRAIN_FILE_LIST: "dataset/MiniDeepGlobeRoadExtraction/train.txt"
    VAL_FILE_LIST: "dataset/MiniDeepGlobeRoadExtraction/val.txt"
    IGNORE_INDEX: 255
    SEPARATOR: '|'
FREEZE: 
    MODEL_FILENAME: "model"
    PARAMS_FILENAME: "params"
    SAVE_DIR: "freeze_model"
MODEL: 
    DEFAULT_NORM_TYPE: "bn"
    MODEL_NAME: "deeplabv3p"
    DEEPLAB:
        BACKBONE: "mobilenet"
        DEPTH_MULTIPLIER: 1.0
        ENCODER_WITH_ASPP: False
        ENABLE_DECODER: False
TEST: 
    TEST_MODEL: "./saved_model/deeplabv3p_mobilenetv2-1-0_bn_deepglobe_road_extraction/final"
TRAIN:
    MODEL_SAVE_DIR: "./saved_model/deeplabv3p_mobilenetv2-1-0_bn_deepglobe_road_extraction/"
    PRETRAINED_MODEL_DIR: "./pretrained_model/deeplabv3p_mobilenetv2-1-0_bn_coco/"
    SNAPSHOT_EPOCH: 10
SOLVER:
    LR: 0.001
    LR_POLICY: "poly"
    OPTIMIZER: "adam"
    NUM_EPOCHS: 300
