_base_: '../_base_/pascal_voc12aug.yml'

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 0.4]

model:
  type: ANN
  backbone:
    type: ResNet50_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  backbone_indices: [2, 3]
  key_value_channels: 256
  inter_channels: 512
  psp_size: [1, 3, 6, 8]
  enable_auxiliary_loss: True
  align_corners: False
  pretrained: null
