_base_: '../_base_/cityscapes.yml'

batch_size: 12  # total: 24
iters: 80000

model:
  type: PPSeg # base: STDCSeg_1
  backbone:
    # STDC_pp_1:ruturns some features
    # STDC_pp_2:returns all features,
    type: STDC_pp_1
    block_type: cat # base cat
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/STDCNet1.tar.gz    # ori cat weights
    #pretrained: pretrained_model/stdc1net_class_pretrained_cat_pp.pdparams # pp cat weights
    #pretrained: pretrained_model/stdc1net_class_pretrained_cat_pp_distill_resnet50_stdc1net_img500w_gpu4_bs64_ep50_lr0.001.pdparams  # distill_2 weights
    #pretrained: pretrained_model/stdc1net_class_pretrained_cat_pp_distill_resnet50_stdc1net_img500w_gpu4_bs64_ep50_lr0.01.pdparams  # distill_3 weights
    atten_type: AttenNone # base: AttenNone
  backbone_indices: [2,3,4]   # [x2, x4, x8, x16, x32]
  head_type: PPSegHead
  arm_type: FusionAdd
  cp_out_ch: 128
  arm_out_chs: [128, 128, 128]
  seg_head_mid_chs: [64, 64, 64]
  resize_mode: bilinear # base: nearest, support:nearest and bilinear

loss:
  types:
    - type: OhemCrossEntropyLoss
    - type: OhemCrossEntropyLoss
    - type: OhemCrossEntropyLoss
    #- type: DetailAggregateLoss
  coef: [1, 1, 1]

test_config:
  aug_eval: True
  scales: 0.5
