_base_: '../_base_/ade20k.yml'

batch_size: 4   # total: 16
iters: 80000

optimizer:
  weight_decay: 5.0e-4  # 4.0e-5 or 5.0e-4

lr_scheduler:
  warmup_iters: 1000
  warmup_start_lr: 1.0e-5

model:
  type: PPSeg
  backbone:
    type: STDC2_pp2
    block_type: cat # base cat
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/STDCNet2.tar.gz    # ori cat weights
  backbone_indices: [2, 3, 4]   # [..., x8_id, x16_id, x32_id]
  feat_nums: [1, 1, 1]   # [..., x8_fn, x16_fn, x32_fn]
  feat_select_mode: last  # support last and even
  head_type: PPSegHead
  arm_type: ARM_Add_Add   # different arm type
  cm_out_ch: 128
  arm_out_chs: [64, 96, 128]   # [..., x8_arm_out_chs, x16_arm_out_chs, x32_arm_out_chs]
  seg_head_mid_chs: [64, 64, 64]
  eval_seg_head_id: 0
  resize_mode: bilinear   # The resize mode for the intermediate interpolate

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 65000  # batch_size * 512 * 512 // 16
    - type: OhemCrossEntropyLoss
      min_kept: 65000
    - type: OhemCrossEntropyLoss
      min_kept: 65000
  coef: [1, 1, 1]

val_dataset:
  transforms:
    - type: ResizeByShort
      short_size: 512
    - type: Normalize
