_base_: '../_base_/cityscapes.yml'

batch_size: 12  # total: 24
iters: 80000

model:
  type: PPSeg
  backbone:
    # STDC_pp_1:ruturns some features, STDC_pp_2:returns all features,
    type: STDC_pp_2
    block_type: cat # base cat
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/STDCNet1.tar.gz    # ori cat weights
    #pretrained: pretrained_model/stdc1net_class_pretrained_cat_pp.pdparams # pp cat weights
    #pretrained: pretrained_model/stdc1net_class_pretrained_cat_pp_distill_resnet50_stdc1net_img500w_gpu4_bs64_ep50_lr0.001.pdparams  # distill_2 weights
    #pretrained: pretrained_model/stdc1net_class_pretrained_cat_pp_distill_resnet50_stdc1net_img500w_gpu4_bs64_ep50_lr0.01.pdparams  # distill_3 weights
  backbone_indices: [2, 3, 4]   # [..., x8_id, x16_id, x32_id]
  feat_nums: [2, 2, 2]   # [..., x8_fn, x16_fn, x32_fn]
  head_type: PPSegHead
  arm_type: FusionAddV1   # different arm type
  cp_out_ch: 128
  arm_out_chs: [64, 64, 64]   # [..., x8_arm_out_chs, x16_arm_out_chs, x32_arm_out_chs]
  seg_head_mid_chs: [64, 64, 64]
  resize_mode: bilinear   # The resize mode for the intermediate interpolate

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 300000
    - type: OhemCrossEntropyLoss
      min_kept: 300000
    - type: OhemCrossEntropyLoss
      min_kept: 300000
    #- type: DetailAggregateLoss
  coef: [1, 1, 1]

train_dataset:
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.125
      max_scale_factor: 1.5
      scale_step_size: 0.125
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: Normalize
  mode: train

test_config:
  aug_eval: True
  scales: 0.5
