_base_: '../_base_/cityscapes.yml'

batch_size: 12
iters: 80000

model:
  type: STDCSeg
  backbone:
    type: STDC1
    pretrained: Null
  pretrained: null

loss:
  types:
    - type: OhemCrossEntropyLoss
    - type: OhemCrossEntropyLoss
    - type: OhemCrossEntropyLoss
    - type: DetailAggregateLoss
  coef: [1, 1, 1, 1]
