batch_size: 8
iters: 100000

train_dataset:
  type: MattingDataset
  dataset_root: test_tipc/data/videomatte10kimage
  train_file: VideoMatte10KImage_train.txt
  transforms:
    - type: LoadImages
    - type: RandomDistort
    - type: RandomBlur
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train
  separator: '|'

val_dataset:
  type: MattingDataset
  dataset_root: test_tipc/data/videomatte10kimage
  val_file: VideoMatte10KImage_val.txt
  transforms:
    - type: LoadImages
    - type: Normalize
  mode: val
  get_trimap: False
  separator: '|'

model:
  type: MODNet
  backbone:
    type: MobileNetV2
    pretrained: https://paddleseg.bj.bcebos.com/matting/models/MobileNetV2_pretrained/model.pdparams
  pretrained: Null

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PiecewiseDecay
  boundaries: [40000, 80000]
  values: [0.01, 0.001, 0.0001]
