_base_: 'fcn_hrnetw48_ccf_256x256_160k.yml'

batch_size: 8
iters: 80000

model:
  type: OCRNet
  pretrained: https://bj.bcebos.com/paddleseg/dygraph/ccf/fcn_hrnetw48_rs_256x256_160k/model.pdparams

learning_rate:
  value: 0.001
  decay:
    type: poly
    power: 0.9
    end_lr: 0.0

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 0.4]
