_base_: '../_base_/cityscapes_1024x1024.yml'

batch_size: 4   # total: 16
iters: 80000    # the iters in papers is 200k, we use 80k

model:
  type: AttaNet
  backbone:
    type: ResNet18_vd
    output_stride: 32
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet18_vd_ssld_v2.tar.gz
  backbone_indices: [-1, -2, -3]
  head_resize_mode: nearest   # origin is nearest, support nearest and bilinear

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 520000
    - type: OhemCrossEntropyLoss
      min_kept: 520000
    - type: OhemCrossEntropyLoss
      min_kept: 520000
  coef: [1, 1, 1]

optimizer:
  weight_decay: 0.0005
