_base_: '../_base_/cityscapes.yml'

batch_size: 2
iters: 160000

model:
  type: SegFormer
  backbone:
    type: mit_b3
    pretrained: mit_b3.pdparams
  embedding_dim: 256
  num_classes: 19

optimizer:
  type: sgd

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  power: 0.9


loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
