_base_: '../deeplabv3p/deeplabv3p_resnet50_isaid_512_512.yml'

model:
  type: DeepLabV3P
  backbone:
    type: ResNet50
    ssl_pretrained: True
    pretrained: https://passl.bj.bcebos.com/models/pixpro_r50_ep100_no_instance_with_linear.pdparams
  num_classes: 16
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null