_base_: '../fcn/fcn_resnet50_isaid_512_512.yml'

model:
  type: FCN
  backbone:
    type: ResNet50
    ssl_pretrained: True
    pretrained: 
  num_classes: 16
  pretrained: Null
  backbone_indices: [-1]
