_base_: '../fcn/fcn_resnet50_isaid_512_512.yml'

model:
  type: FCN
  backbone:
    type: ResNet50
    ssl_pretrained: True
    pretrained: https://passl.bj.bcebos.com/models/pixpro_r50_ep100_no_instance_with_linear.pdparams
  num_classes: 16
  pretrained: Null
  backbone_indices: [-1]
