_base_: '../pspnet/pspnet_resnet50_isaid_512x512_80k.yml'

model:
  type: PSPNet
  backbone:
    type: ResNet50
    ssl_pretrained: True
    pretrained: https://paddleseg.bj.bcebos.com/dygraph/backbone/ssl/pixpro_r50_ep100_no_instance_with_linear.zip
  num_classes: 16
  enable_auxiliary_loss: True
  align_corners: False
  pretrained: null
