_base_: '../upernet/upernet_resnet50_potsdam.yml' 

model:
  type: UPerNet
  backbone:
    type: ResNet50
    ssl_pretrained: True
    pretrained: 
  backbone_indices: [0, 1, 2, 3]
  channels: 512
  dropout_prob: 0.1
  enable_auxiliary_loss: True