_base_: '../upernet/upernet_resnet50_isaid_512_512.yml'

model:
  type: UPerNet
  backbone:
    type: ResNet50
    ssl_pretrained: True
    pretrained: https://passl.bj.bcebos.com/models/mocobyol_r50_ep300_ckpt.pdparams
  backbone_indices: [0, 1, 2, 3]
  channels: 512
  dropout_prob: 0.1
  enable_auxiliary_loss: True