_base_: '../_base_/cityscapes_1024x1024.yml'

batch_size: 3
iters: 120000

model:
  type: DDRNet_23
  augment: False
  pretrained: DDRNet23_imagenet.pdparams

optimizer:
  type: sgd
  weight_decay: 0.0005

loss:
  types:
    - type: OhemCrossEntropyLoss
  coef: [1]

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0.0
  power: 0.9
