shortcut:
  about: Q
  auto_save: X
  change_output_dir: Shift+Z
  clear: Ctrl+Shift+Z
  clear_label: ''
  clear_recent: ''
  close: Ctrl+W
  data_worker: ''
  del_active_polygon: Backspace
  edit_shortcuts: E
  finish_object: Space
  grid_ann: ''
  label_worker: ''
  largest_component: ''
  load_label: ''
  load_param: Ctrl+M
  medical_worker: ''
  model_worker: ''
  open_folder: Shift+A
  open_image: Ctrl+A
  origional_extension: ''
  quick_start: ''
  quit: ''
  redo: Ctrl+Y
  remote_worker: ''
  save: ''
  save_as: ''
  save_coco: ''
  save_json: ''
  save_label: ''
  save_pseudo: ''
  set_worker: ''
  turn_next: F
  turn_prev: S
  undo: Ctrl+Z
