_base_: '../_base_/cityscapes_1024x1024.yml'

model:
  type: BiSeNetV2
  num_classes: 19

optimizer:
  type: sgd
  weight_decay: 0.00004

loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1, 0.7, 0.7, 0.7, 0.7]

batch_size: 4
iters: 160000

learning_rate:
  value: 0.05
  decay:
    type: poly
    power: 0.9
    end_lr: 0.0
