_base_: '../_base_/global_configs.yml'

batch_size: 4
iters: 15000

train_dataset:
  type: Luna16Lobe51
  dataset_root: luna16_lobe51/luna16_lobe51_phase0
  result_dir: luna16_lobe51/luna16_lobe51_phase1
  transforms:
    - type: RandomResizedCrop3D
      size: 128
      scale: [0.8, 1.2]
    - type: RandomRotation3D
      degrees: 90
    - type: RandomFlip3D
  mode: train
  num_classes: 3

val_dataset:
  type: Luna16Lobe51
  dataset_root: luna16_lobe51/luna16_lobe51_phase0
  result_dir: luna16_lobe51/luna16_lobe51_phase1
  num_classes: 3
  transforms: []
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 1.0e-4

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.0003
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
          weight: [0.1, 0.45, 0.45]
        - type: DiceLoss
      coef: [0.5, 0.5]
  coef: [1]
