batch_size: 4
iters: 40000

train_dataset:
  type: PascalVOC
  dataset_root: data/VOCdevkit/
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: PascalVOC
  dataset_root: data/VOCdevkit/
  transforms:
    - type: Padding
      target_size: [512, 512]
    - type: Normalize
  mode: val


optimizer:
  type: Momentum
  learning_rate: 0.0025
  momentum: 0.9
  weight_decay: 1e-4

lr_scheduler:
  type: Poly
  learning_rate: 0.0025


loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
