_base_: '../_base_/mvtec_ad.yml'

batch_size: 1
iters: 5000

model:
  type: STFPM
  backbone:
    type: ResNet18

train_dataset:
  type: Dataset
  num_classes: 1
  dataset_root: /mv_dataset/grid # You need to specify a specific category root in mvtec_ad dataset
  train_path: mv_dataset/grid/train.txt
  transforms:
    - type: Resize
      target_size: [256, 256]
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  mode: train

val_dataset:
  type: Dataset
  num_classes: 1
  dataset_root: dataset/mv_dataset/grid
  val_path: dataset/mv_dataset/grid/val.txt
  transforms:
    - type: Resize
      target_size: [256, 256]
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  mode: val

loss:
  types:
    - type: DistillationLoss
  coef: [1]

optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 1.0e-4

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.4
  end_lr: 0.4
  power: 0.9