_base_: '../_base_/ade20k.yml'

batch_size: 2  # total batch size is 16
iters: 160000

train_dataset:
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

val_dataset:
  transforms:
    - type: Resize
      target_size: [2048, 512]
      keep_ratio: True
      size_divisor: 32
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  
test_config:
  is_slide: True
  crop_size: [512, 512]
  stride: [341, 341]
  
export:
  transforms:
    - type: Resize
      target_size: [2048, 512]
      keep_ratio: True
      size_divisor: 32
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

optimizer:
  _inherited_: False
  type: AdamW
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 1.2e-4
  end_lr: 0
  power: 1.0
  warmup_iters: 1500
  warmup_start_lr: 1.0e-6

loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1, 0.4]

model:
  type: UPerNetViTAdapter
  backbone:
    type: ViTAdapter
    num_heads: 3
    patch_size: 16
    embed_dim: 192
    depth: 12
    mlp_ratio: 4
    drop_path_rate: 0.1
    conv_inplane: 64
    n_points: 4
    deform_num_heads: 6
    cffn_ratio: 0.25
    deform_ratio: 1.0
    interaction_indexes: [[0, 2], [3, 5], [6, 8], [9, 11]]
  backbone_indices: [0, 1, 2, 3]
  channels: 512
  pool_scales: [1, 2, 3, 6]
  dropout_ratio: 0.1
  aux_loss: True
  aux_channels: 256
  pretrained: pretrained_model/upernet_deit_adapter_tiny_512_160_ade20k_from_torch.pdparams